name: Trigger auto deployment for container-app-5tpt4vjrir6ei

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-5tpt4vjrir6ei-AutoDeployTrigger-ef52c662-b065-4f65-bf06-67f5c04c4e0e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5TPT4VJRIR6EI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5TPT4VJRIR6EI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5TPT4VJRIR6EI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5TPT4VJRIR6EI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5TPT4VJRIR6EI_REGISTRY_PASSWORD }}
          containerAppName: container-app-5tpt4vjrir6ei
          resourceGroup: flaskbasica736953e
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


